In [50]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("blastchar/telco-customer-churn")

print("Path to dataset files:", path)
import os

print(os.listdir(path))

Using Colab cache for faster access to the 'telco-customer-churn' dataset.
Path to dataset files: /kaggle/input/telco-customer-churn
['WA_Fn-UseC_-Telco-Customer-Churn.csv']

In [5]:
df = pd.read_csv(path + '/WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [6]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [7]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [28]:
print(X.dtypes)

SeniorCitizen            int64
tenure                   int64
MonthlyCharges         float64
gender_Male               bool
Partner_Yes               bool
                        ...
TotalCharges_997.75       bool
TotalCharges_998.1        bool
TotalCharges_999.45       bool
TotalCharges_999.8        bool
TotalCharges_999.9        bool
Length: 6559, dtype: object

In [34]:
X = df.drop(columns=['customerID', 'Churn'])
y = df['Churn']

In [35]:
X['TotalCharges'] = pd.to_numeric(X['TotalCharges'], errors='coerce')

In [38]:
X = X.fillna(0)

In [39]:
X = pd.get_dummies(X, drop_first=True)

In [40]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state=42)

In [122]:
from imblearn.over_sampling import SMOTE

sm = SMOTE(random_state=42)

X_train_res, y_train_res = sm.fit_resample(X_train, y_train)

In [123]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [124]:
X_train[0]

array([-4.37749204e-01, -4.65683364e-01, -4.73723375e-04, -4.19924521e-01,
       -1.02516569e+00, -9.69578591e-01,  1.53218588e+00,  3.29573443e-01,
       -3.29573443e-01, -8.60523366e-01, -8.87056733e-01, -5.24080751e-01,
       -5.24080751e-01,  1.58094240e+00, -5.24080751e-01, -7.33828011e-01,
       -5.24080751e-01,  1.38479574e+00, -5.24080751e-01, -6.37762944e-01,
       -5.24080751e-01, -7.94748183e-01, -5.24080751e-01,  1.25076217e+00,
        1.91010860e+00, -5.58352808e-01, -1.20000722e+00, -5.27655848e-01,
       -7.09649831e-01,  1.84247002e+00])

In [125]:
y_train

array([0, 0, 1, ..., 0, 1, 0])

#Label Encoding

In [126]:
encode = LabelEncoder()
y_train = encode.fit_transform(y_train)
y_test = encode.transform(y_test)

#from numpy to tensors

In [127]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [128]:
X_train_tensor.shape

torch.Size([5634, 30])

#Model Creation

In [129]:
import torch.nn as nn

class ANN(nn.Module):
    def __init__(self, num_features):
        super().__init__()

        self.hidden1 = nn.Linear(num_features, 64)
        self.relu1 = nn.ReLU()
        self.drop1 = nn.Dropout(0.3)

        self.hidden2 = nn.Linear(64, 32)
        self.relu2 = nn.ReLU()
        self.drop2 = nn.Dropout(0.3)

        self.hidden3 = nn.Linear(32, 16)
        self.relu3 = nn.ReLU()

        self.hidden4 = nn.Linear(16, 8)
        self.relu4 = nn.ReLU()

        self.output = nn.Linear(8, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.hidden1(features)
        out = self.relu1(out)
        out = self.drop1(out)

        out = self.hidden2(out)
        out = self.relu2(out)
        out = self.drop2(out)

        out = self.hidden3(out)
        out = self.relu3(out)

        out = self.hidden4(out)
        out = self.relu4(out)

        out = self.output(out)
        out = self.sigmoid(out)

        return out

In [130]:
!pip install torchinfo

Requirement already satisfied: torchinfo in /usr/local/lib/python3.12/dist-packages (1.8.0)

In [134]:
features = X_test_tensor.shape[1]

In [135]:
X_train_tensor = X_train_tensor.float()
X_test_tensor  = X_test_tensor.float()

In [136]:
model = ANN(features).float()
output = model(X_train_tensor)

In [138]:
from torchinfo import summary

summary(model, input_size=(X_test_tensor.shape))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
ANN                                      [1409, 1]                 --
├─Linear: 1-1                            [1409, 64]                1,984
├─ReLU: 1-2                              [1409, 64]                --
├─Dropout: 1-3                           [1409, 64]                --
├─Linear: 1-4                            [1409, 32]                2,080
├─ReLU: 1-5                              [1409, 32]                --
├─Dropout: 1-6                           [1409, 32]                --
├─Linear: 1-7                            [1409, 16]                528
├─ReLU: 1-8                              [1409, 16]                --
├─Linear: 1-9                            [1409, 8]                 136
├─ReLU: 1-10                             [1409, 8]                 --
├─Linear: 1-11                           [1409, 1]                 9
├─Sigmoid: 1-12                          [1409, 1]                 --
==========================================================================================
Total params: 4,737
Trainable params: 4,737
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 6.67
==========================================================================================
Input size (MB): 0.17
Forward/backward pass size (MB): 1.36
Params size (MB): 0.02
Estimated Total Size (MB): 1.55
==========================================================================================

In [139]:
import torch.optim as optim

criterion = nn.BCELoss()                 #
optimizer = optim.Adam(model.parameters(), lr=0.01)

In [140]:
y_train_tensor = y_train_tensor.view(-1, 1)
y_test_tensor  = y_test_tensor.view(-1, 1)
y_train_tensor = y_train_tensor.float()
y_test_tensor  = y_test_tensor.float()

In [141]:
epochs = 40
for epoch in range(epochs):
  #Forward Pass
  y_pred = model(X_train_tensor)
  # Loss calculation
  loss = criterion(y_pred , y_train_tensor)
  # Backpropagation
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  print(f"Epoch {epoch}, Loss: {loss.item()}")

Epoch 0, Loss: 0.635765790939331
Epoch 1, Loss: 0.6280096769332886
Epoch 2, Loss: 0.6213046312332153
Epoch 3, Loss: 0.607574999332428
Epoch 4, Loss: 0.5855265259742737
Epoch 5, Loss: 0.5543593168258667
Epoch 6, Loss: 0.5189876556396484
Epoch 7, Loss: 0.49334532022476196
Epoch 8, Loss: 0.49471452832221985
Epoch 9, Loss: 0.49721863865852356
Epoch 10, Loss: 0.49479150772094727
Epoch 11, Loss: 0.4836946725845337
Epoch 12, Loss: 0.4731762111186981
Epoch 13, Loss: 0.4678817689418793
Epoch 14, Loss: 0.46656620502471924
Epoch 15, Loss: 0.4677199721336365
Epoch 16, Loss: 0.4688528776168823
Epoch 17, Loss: 0.46678656339645386
Epoch 18, Loss: 0.4632449746131897
Epoch 19, Loss: 0.45695316791534424
Epoch 20, Loss: 0.455515056848526
Epoch 21, Loss: 0.4509955942630768
Epoch 22, Loss: 0.4475231170654297
Epoch 23, Loss: 0.4427645802497864
Epoch 24, Loss: 0.4444965720176697
Epoch 25, Loss: 0.441087931394577
Epoch 26, Loss: 0.4378405213356018
Epoch 27, Loss: 0.4331909120082855
Epoch 28, Loss: 0.4370481073856354
Epoch 29, Loss: 0.43222737312316895
Epoch 30, Loss: 0.4309529960155487
Epoch 31, Loss: 0.42615213990211487
Epoch 32, Loss: 0.4288860559463501
Epoch 33, Loss: 0.426845908164978
Epoch 34, Loss: 0.4251183271408081
Epoch 35, Loss: 0.4262496531009674
Epoch 36, Loss: 0.423093318939209
Epoch 37, Loss: 0.42449691891670227
Epoch 38, Loss: 0.42381736636161804
Epoch 39, Loss: 0.42418181896209717

In [148]:
with torch.no_grad():

    y_pred = model(X_test_tensor)

    y_pred = (y_pred > 0.5).float()

    accuracy = (y_pred == y_test_tensor).float().mean()

    print("Accuracy:", accuracy.item())

Accuracy: 0.8076649904251099

In [149]:
from sklearn.metrics import classification_report

print(classification_report(
    y_test_tensor.numpy(),
    y_pred.numpy()
))

              precision    recall  f1-score   support

         0.0       0.84      0.90      0.87      1036
         1.0       0.67      0.54      0.60       373

    accuracy                           0.81      1409
   macro avg       0.76      0.72      0.74      1409
weighted avg       0.80      0.81      0.80      1409

In [144]:
print(df['Churn'].value_counts())

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [145]:
print(df['Churn'].value_counts(normalize=True))

Churn
No     0.73463
Yes    0.26537
Name: proportion, dtype: float64